### ISSUE TITLE
[UI IMPROVEMENT] Navbar Children Toggle Icon

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [husnainakram09/ecommerce#31]
## Problem
I've seen this is an amazing project indeed but unfortunately I saw there is an misalignment icon (shown in picture below). I think in my opinion it is better to make the page name and the toggle icon on the same line horizontally.

## Solution
I think I could improve it and add HStack into the page label and toggle icon. If you prefer and like my opinion about the UI you can kindly assign me to enhance it. Thanks

![image](https://github.com/husnainakram09/ecommerce/assets/62497214/5d131ee4-528e-4373-b042-0a43f23054df)

**Comment by zainbinshakoor** [comment]
@Dimas-Saputra-Me  "This sounds good. Please feel free to submit a pull request that addresses the issue number."

**Comment by zainbinshakoor** [comment]
@Dimas-Saputra-Me  are you working on it ?

**Comment by Dimas-Saputra-Me** [comment]
@zainbinshakoor Yes, Ill work on it rn. Will pull request in an minutes. Sorry having an internet issue
