### ISSUE TITLE
improve ui design

### ISSUE THREAD

**Issue by Abhinand-s** [husnainakram09/ecommerce#33]
use some new attractive font styles to the interface and add a feature to visualize the product

**Comment by zainbinshakoor** [comment]
Could you provide a detailed explanation of how to visualize the product?

**Comment by Abhinand-s** [comment]
use some hower effect to enlarge the product image and user can rotate it zoom it like that

**Comment by zainbinshakoor** [comment]
It think you can create another task like contact section page i will provide figma design if you want

**Comment by Abhinand-s** [comment]
plz add label hacktoberfest
